Repository AH-64D-Apache-Official-Project/AH-64D, pull requests merged in 2023-05, with the labels that each got.

#253 MPD-ASE-Page Update
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/CfgFunctions.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/CfgWeapons.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/cfgVehicles.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/cfgVehicles/ace.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/headers/systemConstants.h
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/XEH_preInit.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/ase/fn_aseController.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/ase/fn_aseIRJam.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/ase/fn_aseRFJam.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/event/fn_eventInit.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/functions/page/fn_pageASEDraw.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/functions/page/fn_pageASEHandleControl.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/headers/mfdConstants.h
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/pages/ase_draw.hpp
Labels: displays

#252 MPD Add Load Status Page
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/CfgVehicles.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/functions/page/fn_pageDTUDraw.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/functions/page/fn_pageDTUHandleControl.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/headers/mfdConstants.h
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/headers/mpd_defines.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/headers/tsd.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/pages/dtu/loadStatus.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/pages/dtu/root.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/pages/dtu_draw.hpp
Labels: displays

#293 Add Altitude Hold to SFM+
  @AH-64D Apache Longbow/Addons/fza_ah64_common/functions/pid/fn_pidRun.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/CfgUserActions.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/UserActionGroups.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/UserActionsConflictGroups.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/core/fn_coreControlHandle.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/core/fn_coreGetWCAs.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/event/fn_eventInit.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/cfgFunctions.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/core/fn_coreConfig.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/core/fn_coreUpdate.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fmc/fn_fmc.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fmc/fn_fmcAltitudeHold.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fmc/fn_fmcAltitudeHoldEnable.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fmc/fn_fmcAttitudeHoldEnable.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fmc/fn_fmcHoldModesDisable.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fn_getInput.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/simpleRotor/fn_simpleRotor.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/headers/core.hpp
Labels: enhancement, flight model

#295 Add Position Hold to SFM+
  @AH-64D Apache Longbow/Addons/fza_ah64_common/CfgFunctions.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_common/functions/fn_debugDrawCircle.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_common/functions/pid/fn_pidRun.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/core/fn_coreControlHandle.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/core/fn_coreGetWCAs.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/event/fn_eventInit.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/cfgFunctions.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/core/fn_coreConfig.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fmc/fn_fmc.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fmc/fn_fmcAttitudeHold.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fmc/fn_fmcAttitudeHoldEnable.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fmc/fn_fmcForceTrimSet.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fn_getInput.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/simpleRotor/fn_simpleRotor.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/headers/core.hpp
Labels: enhancement, flight model

#302 SFM Plus Feature Addition - Heading Hold
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/XEH_preInit.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/avionics/fn_avionicsSlipIndicator.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/core/fn_coreControlHandle.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/core/fn_coreGetWCAs.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/event/fn_eventInit.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_ihadss/functions/fn_ihadssDraw.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/functions/page/fn_pageFLTDraw.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/cfgFunctions.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/core/fn_coreConfig.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fmc/fn_fmc.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fmc/fn_fmcAttitudeHold.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fmc/fn_fmcForceTrimSet.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fmc/fn_fmcHeadingHold.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/fn_getInput.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/simpleRotor/fn_simpleRotor.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/headers/core.hpp
Labels: enhancement, high priority, flight model

#305 Lima Hellfire Guidance Fix
  @AH-64D Apache Longbow/Addons/fza_ah64_hellfire/functions/fn_arhSeeker.sqf
Labels: high priority

#296 Implemented basic acquisition sources
  @AH-64D Apache Longbow/Addons/fza_ah64_common/CfgFunctions.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_common/functions/fn_currentTurret.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/CfgFunctions.hpp
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/targeting/fn_targetingAcqVec.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/targeting/fn_targetingCurAcq.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_ihadss/functions/fn_constraintBoxDraw.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_ihadss/functions/fn_ihadssDraw.sqf
  @AH-64D Apache Longbow/Addons/fza_ah64_mpd/functions/fn_acqDraw.sqf
Labels: enhancement, medium priority, displays, Work In progress
